<?php include 'core/init.php'; ?>
<?php include 'includes/head.php'; ?>
<?php include 'includes/navigation.php'; ?>
<?php include 'includes/jumbotron.php'; ?>
<?php include 'includes/left_bar.php'; ?>
<?php include 'includes/featured.php'; ?>
<?php include 'includes/right_bar.php'; ?>
<?php include 'includes/login_sign_up_modal.php'; ?>
<?php include 'includes/footer.php'; ?>
